<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LapWinX-DAC8" name="com.github.rest.yaml.test.TestClass" tests="6" failures="1" timestamp="11 Sep 2018 16:14:08 GMT" time="9.844" errors="0">
  <testcase name="setupTest" time="1.124" classname="com.github.rest.yaml.test.TestClass">
    <failure type="java.lang.AssertionError" message="
Expected: &lt;201&gt;
     but: was &lt;200&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <201>
     but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.github.rest.yaml.test.RestResponse.doAssert(RestResponse.java:27)
at com.github.rest.yaml.test.TestClass.setupTest(TestClass.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- setupTest -->
  <testcase name="setupTest" time="1.076" classname="com.github.rest.yaml.test.TestClass"/>
  <testcase name="setupTest" time="1.188" classname="com.github.rest.yaml.test.TestClass"/>
  <testcase name="setupTest" time="1.050" classname="com.github.rest.yaml.test.TestClass"/>
  <testcase name="setupTest" time="4.357" classname="com.github.rest.yaml.test.TestClass"/>
  <testcase name="setupTest" time="1.049" classname="com.github.rest.yaml.test.TestClass"/>
</testsuite> <!-- com.github.rest.yaml.test.TestClass -->
